### ISSUE TITLE
shopping-cart

### ISSUE THREAD

**Issue by vinnie1329** [RedHatTraining/DO400-apps#54]
It seems the shopping-cart directory is missing kubefiles/application-template.yml referenced in the 8.3 Guided Exercise.

oc process \
-n RHT_OCP4_DEV_USER-shopping-cart-production \
-f kubefiles/application-template.yml \
-p QUAY_USER_OR_GROUP=YOUR_QUAY_USER \
-p APP_ENVIRONMENT=production \
| oc apply -n RHT_OCP4_DEV_USER-shopping-cart-production -f -

**Comment by jramcast** [comment]
Hi @vinnie1329 . Please use the `shopping-cart` directory from the `solutions`  branch.

https://github.com/RedHatTraining/DO400-apps/tree/solutions/shopping-cart

**Comment by vinnie1329** [comment]
Thank you.
