### ISSUE TITLE
Solution for Chapter07

### ISSUE THREAD

**Issue by jasonwcc** [RedHatTraining/DO400-apps#61]
Hi

Can't help but notice there is no solution given for Chapter 07.

With solutions, students would be able to solve and fix their code respectively.

Rgrds

**Comment by stencell** [comment]
Hi @jasonwcc, can you provide some more detail on which exact guided exercise or lab is missing what you expect? At a quick glance, I see solutions for the lab exercises in DO400, so I am not sure if you have the problem elsewhere or I am missing something.

Also, in the future, it would be easier to have you use the "Feedback" button in ROL to report this. That will open a Jira issue and associate it to the actual course repo - not this example apps repo. It will also provide more clarity and detail on which page/exercise/lab you see the problem and our LX team can do some triage before sending it our way.

Thanks!
